### ISSUE TITLE
`undefined symbol` error when running chapter 7 notebooks on a GPU instance

### ISSUE THREAD

**Issue by raphaelmerx** [huggingface/notebooks#120]
## Description

Running the chapter 7 notebooks on a GPU Colab instance throws the following error during training:
```
RuntimeError: Failed to import transformers.training_args because of the following error (look up to see its traceback):
/usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at13_foreach_erf_EN3c108ArrayRefINS_6TensorEEE
```

Could this be related to the installation of Pytorch from https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl introduced in https://github.com/huggingface/notebooks/commit/2dedfdf2f24760a7369f3d8a0741a948a3ec8cd9?

Note that the notebooks are installing `transformers==4.12.5` and `torch @ https://download.pytorch.org/whl/cu111/torch-1.10.0%2Bcu111-cp37-cp37m-linux_x86_64.whl`

**Comment by raphaelmerx** [comment]
Removing `! pip install accelerate cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.9-cp37-cp37m-linux_x86_64.whl` in the first cell fixes the issue

**Comment by emmanuelchauvin** [comment]
I just tested what raphaelmerx proposed without sucess !

Same issue.

**Comment by raphaelmerx** [comment]
@emmanuelchauvin  Can you try the following notebook? https://colab.research.google.com/drive/1Dvvl3cTpsH3nsSIX8qZ8ZRFMOCjoc-YF?usp=sharing

It's a copy of the chapter 7 section 3 notebook, with the line mentioned in https://github.com/huggingface/notebooks/issues/120#issuecomment-982413817 commented out, and running on a P100 GPU. Training ran without issues.

**Comment by raphaelmerx** [comment]
That line was added by @sgugger in https://github.com/huggingface/notebooks/commit/2dedfdf2f24760a7369f3d8a0741a948a3ec8cd9, pinging him to see if they should be removed or what he thinks the appropriate fix would be.

**Comment by sgugger** [comment]
This line should not be run if you're not planning to run the training on TPUs, will update the notebooks to show that.

**Comment by raphaelmerx** [comment]
Thanks for the fix, however your commit https://github.com/huggingface/notebooks/commit/6d2301317b8e742c7a30eec5f77e4ef1762e85a1 also removed `pip install accelerate`, which is used by some notebooks, e.g `chapter7/section3_pt.ipynb`

**Comment by sgugger** [comment]
Ah good catch! Added it back on a separate line.

**Comment by raphaelmerx** [comment]
Thank you for the fixes, closing this issue then.
