### ISSUE TITLE
SageMaker samples return error on SageMaker Notebook Instances

### ISSUE THREAD

**Issue by la-cruche** [huggingface/notebooks#161]
Hi,

those 2 samples don't work anymore on SageMaker Notebook instances

1. https://github.com/huggingface/notebooks/tree/master/sagemaker/01_getting_started_pytorch
2. https://github.com/huggingface/notebooks/tree/master/sagemaker/06_sagemaker_metrics

```

import botocore
from datasets.filesystems import S3FileSystem

s3 = S3FileSystem()  

# save train_dataset to s3
training_input_path = f's3://{sess.default_bucket()}/{s3_prefix}/train'
train_dataset.save_to_disk(training_input_path,fs=s3)

# save test_dataset to s3
test_input_path = f's3://{sess.default_bucket()}/{s3_prefix}/test'
test_dataset.save_to_disk(test_input_path,fs=s3)
```

returns `NoCredentialsError: Unable to locate credentials` when ran as-is. This was not the case previously.

**Comment by philschmid** [comment]
Do you know if SageMaker changed something on how they provide credentials?
