### ISSUE TITLE
Add a notebook for fine-tuning video classification

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/notebooks#258]
We have a couple of video models: https://huggingface.co/models?pipeline_tag=video-classification&sort=downloads. 

Considering videos are an essential modality to tackle with lots of exciting applications, it is a good idea to have a notebook tutorial showing how to fine-tune a video classification model. 

We don't have involved support for videos in `datasets` yet ([issue](https://github.com/huggingface/datasets/issues/5032)), so, the tutorial will rely on `decord` and `torchvision` and will also leverage different utilities from `datasets` when necessary. I also understand that videos in `transformers` are new and may go through different transition phases. So, when there's better support for videos in `datasets` I can update the notebook as well.

**Comment by fcakyon** [comment]
I have PhD qual in 3 weeks. I will be busy with till then. If no one picks this issue I can work on video fine-tuning notebook + video dataset integration (I also have [timesformer video transformer](https://github.com/huggingface/transformers/pull/18908) pr open)

**Comment by sayakpaul** [comment]
@fcakyon thanks for letting me know. I was thinking of starting with a notebook without the video dataset integration (i.e., using decord and torchvision) to make some progress. 

Later we could integrate the video dataset support from `datasets` when that is available. 

Happy to collaborate :)

**Comment by sayakpaul** [comment]
Thank you!

**Comment by bayesianist** [comment]
Finally, I think there is a missing code to define resize_to variable 
if "shortest_edge" in image_processor.size:
    height = width = image_processor.size["shortest_edge"]
else:
    height = image_processor.size["height"]
    width = image_processor.size["width"]
resize_to = (height, width)
