### ISSUE TITLE
sd_dreambooth_inference.ipynb fails to load models

### ISSUE THREAD

**Issue by jbpacker** [huggingface/notebooks#278]
I've been getting errors loading models with the inference script:

![PNG image](https://user-images.githubusercontent.com/11084932/205428367-7f946c5a-774c-40b5-9178-7f541b29d1d1.jpeg)

I was able to resolve by using a newer version of the diffusers library in sd_dreambooth_inference.ipynb.

I was able to get it working with the following:

I replaced:
```
!pip install -qqq diffusers==0.4.1 transformers gradio ftfy 
```
with this:
```
!pip install -U -qq git+https://github.com/huggingface/diffusers.git

!pip install -qqq transformers gradio ftfy 
```

**Comment by anton-l** [comment]
Should be solved in the updated notebook! (https://github.com/huggingface/notebooks/pull/298)
