### ISSUE TITLE
stable_diffusion.ipynb: Can't get past the "make sure you're logged in with `huggingface-cli login" error message

### ISSUE THREAD

**Issue by prmunn** [huggingface/notebooks#284]
I can't get past the "make sure you're logged in with `huggingface-cli login" error message. I created a hugging face account and generated a write token. I then entered it after executing notebook_login() and got a message saying the token had been saved and login was successful. However, when I execute the next block I code I continually get the "make sure you're logged in with `huggingface-cli login" error message. I checked stackoverflow and it seems like a lot of people are having the same issue, but none of the suggested solutions is working.

**Comment by k1ng** [comment]
I have same problem
![Снимок экрана 2022-12-08 в 20 37 03](https://user-images.githubusercontent.com/1550243/206524141-bf90e0e3-a107-416e-8075-203d7ac0c2a5.png)

**Comment by k1ng** [comment]
I update diffusers from version 0.4.0 to 0.9.0 and the problem was solved.
![image](https://user-images.githubusercontent.com/1550243/206526851-f936d515-20a7-4dde-b170-611ff6534302.png)

**Comment by anton-l** [comment]
Should be solved in the updated notebooks :) (https://github.com/huggingface/notebooks/pull/298)

**Comment by RayNeverLearns** [comment]
I am having the same issue and I am using diffusers v0.11.1. Please help.

![image](https://github.com/user-attachments/assets/6abad8cd-6c32-429e-9f02-a79efc85b7ca)

![image](https://github.com/user-attachments/assets/7a1e6091-4a3d-4fc1-acf3-908848c9a915)
