### ISSUE TITLE
24_train_bloom_peft_lora notebook 8-bit  training is not supported yet.

### ISSUE THREAD

**Issue by oguuzhansahin** [huggingface/notebooks#381]
I was try to reproduce tranining bloom with aws sagemaker and lora notebook  on AWS Sagemaker notebook. It threw me an error like:

`ValueError: The model you want to train is loaded in 8-bit precision. Training  an 8-bit model is not supported yet.`
![8biterror](https://github.com/huggingface/notebooks/assets/23113621/08e0ea8e-669d-456f-ace6-25ec40654bc6)

**Comment by philschmid** [comment]
Did you make any modifications to the notebook?

**Comment by Donyme** [comment]
No change in script, this error is thrown when you directly run the script on sagemaker notebook.

**Comment by philschmid** [comment]
Rerun it and it worked, did you copy the `requirements.txt` as well?

**Comment by WZNT-KimHyeJin** [comment]
Same here... I need help T_T

**Comment by WZNT-KimHyeJin** [comment]
Install the pip file and copy requirements.txt properly. Re-run that notebook, then you can see it's working!
