### ISSUE TITLE
Update SM PySDK Version to >= 2.163.0 for Falcon models. 

### ISSUE THREAD

**Issue by kirubs2code** [huggingface/notebooks#393]
The SM deployment for Falcon 7B model work only for SM PySDK version >= 2.163.0. Can this be added in HF model hub & Blogs ? Thanks.

Blog - https://huggingface.co/blog/sagemaker-huggingface-llm

NoteBook change in llm-hosting-container - https://github.com/awslabs/llm-hosting-container/blob/main/examples/huggingface/huggingface-large-model-inference-falcon-7b.ipynb

**Comment by jeffboudier** [comment]
Blog PR: https://github.com/huggingface/blog/pull/1201

Notebook has already been changed: https://github.com/awslabs/llm-hosting-container/commit/c64e946cab09b39d87c38b3ee75114b0a1721cd9
