### ISSUE TITLE
Clarify notebooks are generated from the docs

### ISSUE THREAD

**Issue by stevhliu** [huggingface/notebooks#423]
I've seen several instances of users updating the notebooks here only for their changes to get overwritten by the doc-builder. Should we make a note of this in the main `README` like how the 🤗 [Transformers](https://github.com/huggingface/notebooks/tree/main/transformers_doc#-transformers-doc-notebooks) folder does? cc @sgugger

**Comment by sgugger** [comment]
Not sure why I'm pinged. We do it for Transformers already, so I guess you wanted to ping the maintainers of another repo?

**Comment by stevhliu** [comment]
I was thinking about adding it to the main [`README`](https://github.com/huggingface/notebooks#notebooks) of the notebooks repo, but if you think its better we can also add it to each of the repo folders :)

**Comment by sgugger** [comment]
There are notebooks that are not doc notebooks and are not auto-updated: all examples for instance.

**Comment by stevhliu** [comment]
Gotcha! I'll ping the other maintainers and add it to the subfolders where the doc notebooks are automatically updated then. Thanks!
