### ISSUE TITLE
Can't run the SageMaker PyTorch Getting Started notebook 

### ISSUE THREAD

**Issue by rabowskyb** [huggingface/notebooks#65]
In the [Huggingface Sagemaker-sdk - Getting Started Demo](https://github.com/huggingface/notebooks/blob/master/sagemaker/01_getting_started_pytorch/sagemaker-notebook.ipynb), when I run the load dataset cell I get the error pasted below.  I am running the notebook in SageMaker Studio, I have tried both the Data Science and PyTorch 1.6 kernels.  

---------------------------------------------------------------------------
NonMatchingSplitsSizesError               Traceback (most recent call last)
<ipython-input-3-f679b4883c2d> in <module>
      1 # load dataset
----> 2 dataset = load_dataset(dataset_name)
      3 
      4 # download tokenizer
      5 tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)

/opt/conda/lib/python3.6/site-packages/datasets/load.py in load_dataset(path, name, data_dir, data_files, split, cache_dir, features, download_config, download_mode, ignore_verifications, keep_in_memory, save_infos, script_version, use_auth_token, **config_kwargs)
    749         try_from_hf_gcs=try_from_hf_gcs,
    750         base_path=base_path,
--> 751         use_auth_token=use_auth_token,
    752     )
    753 

/opt/conda/lib/python3.6/site-packages/datasets/builder.py in download_and_prepare(self, download_config, download_mode, ignore_verifications, try_from_hf_gcs, dl_manager, base_path, use_auth_token, **download_and_prepare_kwargs)
    573                     if not downloaded_from_gcs:
    574                         self._download_and_prepare(
--> 575                             dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
    576                         )
    577                     # Sync info

/opt/conda/lib/python3.6/site-packages/datasets/builder.py in _download_and_prepare(self, dl_manager, verify_infos, **prepare_split_kwargs)
    660 
    661         if verify_infos:
--> 662             verify_splits(self.info.splits, split_dict)
    663 
    664         # Update the info object with the splits.

/opt/conda/lib/python3.6/site-packages/datasets/utils/info_utils.py in verify_splits(expected_splits, recorded_splits)
     72     ]
     73     if len(bad_splits) > 0:
---> 74         raise NonMatchingSplitsSizesError(str(bad_splits))
     75     logger.info("All the splits matched successfully.")
     76 

NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='test', num_bytes=32660064, num_examples=25000, dataset_name='imdb'), 'recorded': SplitInfo(name='test', num_bytes=9982987, num_examples=7726, dataset_name='imdb')}, {'expected': SplitInfo(name='train', num_bytes=33442202, num_examples=25000, dataset_name='imdb'), 'recorded': SplitInfo(name='train', num_bytes=0, num_examples=0, dataset_name='imdb')}, {'expected': SplitInfo(name='unsupervised', num_bytes=67125548, num_examples=50000, dataset_name='imdb'), 'recorded': SplitInfo(name='unsupervised', num_bytes=0, num_examples=0, dataset_name='imdb')}]

**Comment by SergioMarreroMarrero** [comment]
I have exactly the same problem.

Did you find the solution?

Please can someone help here?
