### ISSUE TITLE
01_getting_started_pytorch notebook - Hyperparameters sent by the client aren't passed to the Training Arguments

### ISSUE THREAD

**Issue by hellosamstuart** [huggingface/notebooks#67]
Hello!

Reopening an issue connected to this thread here: 
* https://github.com/huggingface/notebooks/issues/52 

Thank you HuggingFace team for all you do! This summer I have been working from this notebook when I noticed a gap I will discuss below. PS - this is my first GitHub issue, if you have any feedback.

<h2><b>Description (same as 52)</b></h2>
The hyperparameters sent by the client have an underscore in them (e.g. output_data_dir), whereas those received by the argparser have a hyphen (e.g. output-data-dir). Therefore, values do not get propagated through the train.py file. 

<h2><b>Why another issue?</b></h2>
There have been recent commits resolving the above-linked issue in most of the notebooks. However I noticed the commit to fix this issue for Pytorch missed the second half of the typos (commit fixed train-batch-size and eval-batch-size, but still need to fix output-data-dir and model-dir).

Relevant Commits
* https://github.com/huggingface/notebooks/pull/62/commits/9df51d5e28036dcfbe15eb1a3e6ef2dfd5d9924c (tensorflow + others)
* https://github.com/huggingface/notebooks/commit/c3fa5b5372d037d1067dd31e20e77e6a69320ce0 (half the fix for pytorch)

<h2><b>Files</b></h2>
I have tested the solution on these files

notebooks/sagemaker/01_getting_started_pytorch/sagemaker-notebook.ipynb
notebooks/sagemaker/01_getting_started_pytorch/scripts/train.py

<h2><b>Solution</b></h2>
In the train.py file, swap these lines -

parser.add_argument("--output-data-dir", type=str, default=os.environ["SM_OUTPUT_DATA_DIR"])
parser.add_argument("--model-dir", type=str, default=os.environ["SM_MODEL_DIR"])
with these

parser.add_argument("--output_data_dir", type=str, default=os.environ["SM_OUTPUT_DATA_DIR"])
parser.add_argument("--model_dir", type=str, default=os.environ["SM_MODEL_DIR"])

**Comment by hellosamstuart** [comment]
Hi @philschmid! Got a tip from my colleague who filed the issue #52 that tagging you here would be best for Sagemaker issues. Please see my note above about a gap a recent commit leaving a remaining issue behind. Thanks!

**Comment by philschmid** [comment]
Hey @hellosamstuart, 
Thank you for finding those! Should be merged and good to use. 

You must have spent way too much time creating this issue. It looks so well structured. BTW you can always open a PR with the fix too
