### ISSUE TITLE
I can't run deploy_transformer_model_from_hf_hub.ipynb on AWS Sagemaker notebook instance

### ISSUE THREAD

**Issue by farshadsm** [huggingface/notebooks#70]
Hi, 
When I ran deploy_transformer_model_from_hf_hub.ipynb on AWS Sagemaker notebook instance with conda_pytorch_p36 kernel, I got the following error message for "from sagemaker.huggingface import HuggingFaceModel" command:

ImportError: cannot import name 'HuggingFaceModel'

The official website says that I should use "from sagemaker.huggingface.model import HuggingFaceModel" instead of "from 
sagemaker.huggingface import HuggingFaceModel" which is used in "deploy_transformer_model_from_hf_hub.ipynb". See the following two resources for your reference:
1) https://sagemaker.readthedocs.io/en/stable/frameworks/huggingface/sagemaker.huggingface.html#hugging-face-model
2) https://huggingface.co/docs/sagemaker/inference

I just want to inform you that I have already updated "sagemaker" package in the Notebook instance by running "pip install sagemaker --upgrade"

After using "from sagemaker.huggingface.model import HuggingFaceModel", I got rid of the error message mentioned above and I was able to run the following code block:

from sagemaker.huggingface import HuggingFaceModel
import sagemaker 
role = sagemaker.get_execution_role()

hub = {
  'HF_MODEL_ID':'distilbert-base-uncased-distilled-squad', 
  'HF_TASK':'question-answering' # NLP task you want to use for predictions
}

huggingface_model = HuggingFaceModel(
   env=hub,
   role=role, 
   transformers_version="4.6", 
   pytorch_version="1.7",
   py_version="py36",
)

However, I couldn't run the following code block which generated an error message, which I've attached in a doc file.
`
predictor = huggingface_model.deploy(
   initial_instance_count=1,
   instance_type="ml.m5.xlarge"
)
`

I'd appreciate your help.

Best,
Farshad

[deploy_error_message.docx](https://github.com/huggingface/notebooks/files/6978741/deploy_error_message.docx)

**Comment by farshadsm** [comment]
Hi,
Just an update. Interestingly, I was able to run the following code from my local machine. So, it seems that there's a problem with Sagemaker Notebook Instance. 

`
from sagemaker.huggingface import HuggingFaceModel
import boto3

iam_client = boto3.client('iam')
role = iam_client.get_role(RoleName='{IAM_ROLE_WITH_SAGEMAKER_PERMISSIONS}')['Role']['Arn']

# Hub Model configuration. https://huggingface.co/models
hub = {
	'HF_MODEL_ID':'facebook/bart-large-mnli',
	'HF_TASK':'zero-shot-classification'
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	transformers_version='4.6.1',
	pytorch_version='1.7.1',
	py_version='py36',
	env=hub,
	role=role, 
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
	initial_instance_count=1, # number of instances
	instance_type='ml.m5.xlarge' # ec2 instance type
)

input_data = {
  "inputs": "Hi, I recently bought a device from your company but it is not working as advertised and I would like to get reimbursed!",
  "parameters": {
    "candidate_labels": ["refund", "legal", "faq"]
  }
}

predictor.predict(input_data)
`

Best,
Farshad

**Comment by philschmid** [comment]
Hi @farshadsm,

you might need to run `pip install sagemaker --upgrade` on the SageMaker Notebook instance to work. I am not sure how regularly AWS is updating the kernels.
